In [29]:
# Importing libraries

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [30]:
# Defining column names for property datasets

transactions_columns = [
    'Transaction Unique Identifier',
    'Price',
    'Date of Transfer',
    'Postcode',
    'Property Type',
    'Old/New',
    'Duration',
    'PAON',
    'SAON',
    'Street',
    'Locality',
    'Town/City',
    'District',
    'County',
    'PPD Category Type',
    'Record Status'
]

In [31]:
# Reading property transactions in 2020

df_transactions_2020 = pd.read_csv('../data/raw/transactions_2020.csv', header=None, names=transactions_columns)

df_transactions_2020

,Transaction Unique Identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status
0,{AC07BBCF-E34C-0445-E053-6C04A8C01E31},150000,2020-06-12 00:00,WA7 5BU,D,N,F,12,NaN,ECCLESTON DRIVE,NaN,RUNCORN,HALTON,HALTON,A,A
1,{AC07BBCF-E34D-0445-E053-6C04A8C01E31},375000,2020-03-27 00:00,SK9 4ET,D,N,F,26,NaN,STANNEYLANDS DRIVE,NaN,WILMSLOW,CHESHIRE EAST,CHESHIRE EAST,A,A
2,{AC07BBCF-E34E-0445-E053-6C04A8C01E31},140000,2020-03-04 00:00,CW9 8BP,T,N,F,7,NaN,ADLINGTON DRIVE,NaN,NORTHWICH,CHESHIRE WEST AND CHESTER,CHESHIRE WEST AND CHESTER,A,A
3,{AC07BBCF-E34F-0445-E053-6C04A8C01E31},95000,2020-04-30 00:00,WA8 8UT,S,N,F,410,NaN,HALE ROAD,NaN,WIDNES,HALTON,HALTON,A,A
4,{AC07BBCF-E350-0445-E053-6C04A8C01E31},170000,2020-04-30 00:00,WA5 3LZ,S,N,F,2,NaN,CLARENCE AVENUE,GREAT SANKEY,WARRINGTON,WARRINGTON,WARRINGTON,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896669,{BA558B32-2AB7-76EF-E053-6B04A8C0B4B7},185000,2020-11-06 00:00,SL3 8EX,F,N,L,26,NaN,TILBURY WALK,NaN,SLOUGH,SLOUGH,SLOUGH,A,A
896670,{BA558B32-2AB8-76EF-E053-6B04A8C0B4B7},370000,2020-11-30 00:00,RG19 8XR,D,N,F,22,NaN,MONTAGUE DRIVE,GREENHAM,THATCHAM,WEST BERKSHIRE,WEST BERKSHIRE,A,A
896671,{BA558B32-2AB9-76EF-E053-6B04A8C0B4B7},289950,2020-11-20 00:00,RG17 9UP,S,N,F,9,NaN,STATION ROAD,KINTBURY,HUNGERFORD,WEST BERKSHIRE,WEST BERKSHIRE,A,A
896672,{BA558B32-2ABA-76EF-E053-6B04A8C0B4B7},400000,2020-10-23 00:00,RG7 4GX,S,N,F,72,NaN,FALLOWS ROAD,PADWORTH,READING,WEST BERKSHIRE,WEST BERKSHIRE,A,A
896673,{BA558B32-2ABB-76EF-E053-6B04A8C0B4B7},425000,2020-12-18 00:00,GU47 8PW,D,N,F,24,NaN,BROOM ACRES,NaN,SANDHURST,BRACKNELL FOREST,BRACKNELL FOREST,A,A

In [32]:
# Reading property transactions in 2021

df_transactions_2021 = pd.read_csv('../data/raw/transactions_2021.csv', header=None, names=transactions_columns)

df_transactions_2021

,Transaction Unique Identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status
0,{D707E535-5720-0AD9-E053-6B04A8C067CC},260000,2021-08-06 00:00,SO45 2HT,T,N,F,17,NaN,PERRYWOOD CLOSE,HOLBURY,SOUTHAMPTON,NEW FOREST,HAMPSHIRE,A,A
1,{D707E535-5721-0AD9-E053-6B04A8C067CC},375000,2021-09-01 00:00,SO23 7FR,S,N,F,1,NaN,BOXALL GARDENS,KINGS WORTHY,WINCHESTER,WINCHESTER,HAMPSHIRE,A,A
2,{D707E535-5723-0AD9-E053-6B04A8C067CC},132000,2021-06-28 00:00,SP11 6RL,F,N,L,2,NaN,SEDGE ROAD,NaN,ANDOVER,TEST VALLEY,HAMPSHIRE,A,A
3,{D707E535-5724-0AD9-E053-6B04A8C067CC},295000,2021-09-10 00:00,SP11 6TU,T,N,F,21,NaN,NAP CLOSE,NaN,ANDOVER,TEST VALLEY,HAMPSHIRE,A,A
4,{D707E535-5725-0AD9-E053-6B04A8C067CC},360000,2021-08-27 00:00,SO51 0AX,T,N,F,130,NaN,FREEMANTLE ROAD,NaN,ROMSEY,TEST VALLEY,HAMPSHIRE,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1280226,{D707E536-89CA-0AD9-E053-6B04A8C067CC},158000,2021-12-17 00:00,NN2 7RA,T,N,F,40,NaN,WEST RIDGE,NaN,NORTHAMPTON,WEST NORTHAMPTONSHIRE,WEST NORTHAMPTONSHIRE,B,A
1280227,{D707E536-89CB-0AD9-E053-6B04A8C067CC},105000,2021-05-26 00:00,NN11 9AU,F,N,L,10,NaN,COLERIDGE WALK,NaN,DAVENTRY,WEST NORTHAMPTONSHIRE,WEST NORTHAMPTONSHIRE,B,A
1280228,{D707E536-89CC-0AD9-E053-6B04A8C067CC},239000,2021-10-05 00:00,NN1 3JE,T,N,F,39,NaN,CLARE STREET,NaN,NORTHAMPTON,WEST NORTHAMPTONSHIRE,WEST NORTHAMPTONSHIRE,B,A
1280229,{D707E536-89CD-0AD9-E053-6B04A8C067CC},190000,2021-09-08 00:00,NN18 8QS,T,N,F,5,NaN,GOODWOOD CLOSE,OAKLEY,CORBY,NORTH NORTHAMPTONSHIRE,NORTH NORTHAMPTONSHIRE,B,A
1280230,{D707E536-89CF-0AD9-E053-6B04A8C067CC},210000,2021-10-05 00:00,NN1 3RN,T,N,F,54,NaN,LORNE ROAD,NaN,NORTHAMPTON,WEST NORTHAMPTONSHIRE,WEST NORTHAMPTONSHIRE,B,A

In [33]:
# Reading property transactions in 2022

df_transactions_2022 = pd.read_csv('../data/raw/transactions_2022.csv', header=None, names=transactions_columns)

df_transactions_2022

,Transaction Unique Identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status
0,{DBA933F9-D5BC-669D-E053-6B04A8C0AD56},205000,2022-02-18 00:00,DL9 4RS,D,N,F,26,NaN,MAPLE AVENUE,COLBURN,CATTERICK GARRISON,RICHMONDSHIRE,NORTH YORKSHIRE,A,A
1,{DBA933F9-D5BE-669D-E053-6B04A8C0AD56},220000,2022-02-14 00:00,YO12 7ND,S,N,F,3,NaN,PEASHOLM GARDENS,NaN,SCARBOROUGH,SCARBOROUGH,NORTH YORKSHIRE,A,A
2,{DBA933F9-D5C0-669D-E053-6B04A8C0AD56},775000,2022-02-22 00:00,HG5 0TT,D,N,F,WATERS NOOK,NaN,YORK ROAD,NaN,KNARESBOROUGH,HARROGATE,NORTH YORKSHIRE,A,A
3,{DBA933F9-D5C6-669D-E053-6B04A8C0AD56},450000,2022-03-04 00:00,YO31 1BU,D,N,F,116,NaN,STOCKTON LANE,NaN,YORK,YORK,YORK,A,A
4,{DBA933F9-D5CC-669D-E053-6B04A8C0AD56},175000,2022-02-25 00:00,LA2 7EB,T,N,F,BORRANS COTTAGES,3,BURTON ROAD,LOWER BENTHAM,LANCASTER,CRAVEN,NORTH YORKSHIRE,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074561,{EA3278A9-E061-2676-E053-6B04A8C015F8},205000,2022-06-27 00:00,SK14 4AF,S,N,L,71,NaN,DANBY CLOSE,NaN,HYDE,TAMESIDE,GREATER MANCHESTER,A,A
1074562,{EA3278A9-E062-2676-E053-6B04A8C015F8},195000,2022-09-02 00:00,BL2 5QZ,T,N,F,14,NaN,BANKFIELD CLOSE,AINSWORTH,BOLTON,BURY,GREATER MANCHESTER,A,A
1074563,{EA3278A9-E064-2676-E053-6B04A8C015F8},186000,2022-07-22 00:00,WN6 0SX,S,N,L,10,NaN,BARBROOK CLOSE,STANDISH,WIGAN,WIGAN,GREATER MANCHESTER,A,A
1074564,{EA3278A9-E065-2676-E053-6B04A8C015F8},225000,2022-08-19 00:00,M45 7FL,S,N,F,29,NaN,BURY NEW ROAD,WHITEFIELD,MANCHESTER,BURY,GREATER MANCHESTER,A,A
1074565,{EA3278A9-E066-2676-E053-6B04A8C015F8},150000,2022-07-27 00:00,M34 3HU,T,N,F,29,NaN,BOOTH STREET,DENTON,MANCHESTER,TAMESIDE,GREATER MANCHESTER,A,A

In [34]:
# Reading property transactions in 2023

df_transactions_2023 = pd.read_csv('../data/raw/transactions_2023.csv', header=None, names=transactions_columns)

df_transactions_2023

,Transaction Unique Identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status
0,{01EB45F0-6229-40F3-E063-4704A8C05FDE},208000,2023-06-14 00:00,RH15 0DZ,F,N,L,62,NaN,THE WARREN,NaN,BURGESS HILL,MID SUSSEX,WEST SUSSEX,A,A
1,{01EB45F0-622A-40F3-E063-4704A8C05FDE},193000,2023-02-10 00:00,BN13 1NT,F,N,L,"CATHERINE LODGE, 52",FLAT 31,BOLSOVER ROAD,NaN,WORTHING,WORTHING,WEST SUSSEX,A,A
2,{01EB45F0-622B-40F3-E063-4704A8C05FDE},185000,2023-05-26 00:00,BN11 2BU,F,N,L,MARIK MEWS,FLAT 3,SELDEN LANE,NaN,WORTHING,WORTHING,WEST SUSSEX,A,A
3,{01EB45F0-622C-40F3-E063-4704A8C05FDE},187500,2023-06-09 00:00,BN16 3BJ,F,N,L,ABBOTSWOOD,FLAT 34,STATION ROAD,RUSTINGTON,LITTLEHAMPTON,ARUN,WEST SUSSEX,A,A
4,{01EB45F0-622D-40F3-E063-4704A8C05FDE},265000,2023-06-28 00:00,BN11 4JS,F,N,L,"ASPEN COURT, 40 - 42",FLAT 9,ST BOTOLPHS ROAD,NaN,WORTHING,WORTHING,WEST SUSSEX,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857480,{06C9F487-585E-9388-E063-4804A8C0BD98},172500,2023-03-03 00:00,CM8 2AW,F,N,L,WHITEHALL COURT,FLAT 28,NEWLAND STREET,NaN,WITHAM,BRAINTREE,ESSEX,A,A
857481,{06C9F487-585F-9388-E063-4804A8C0BD98},375000,2023-08-17 00:00,CM8 2DJ,S,N,F,20,NaN,THE AVENUE,NaN,WITHAM,BRAINTREE,ESSEX,A,A
857482,{06C9F487-5860-9388-E063-4804A8C0BD98},610000,2023-08-22 00:00,CO3 3NR,D,N,F,41,NaN,CAMBRIDGE ROAD,NaN,COLCHESTER,COLCHESTER,ESSEX,A,A
857483,{06C9F487-5861-9388-E063-4804A8C0BD98},525000,2023-07-31 00:00,CM15 9NP,S,N,F,12,NaN,ELIZABETH ROAD,PILGRIMS HATCH,BRENTWOOD,BRENTWOOD,ESSEX,A,A
857484,{06C9F487-5862-9388-E063-4804A8C0BD98},326000,2023-07-28 00:00,SS13 1JH,S,N,F,30,NaN,CHARLESTON AVENUE,NaN,BASILDON,BASILDON,ESSEX,A,A

In [35]:
# Reading property transactions in 2024

df_transactions_2024 = pd.read_csv('../data/raw/transactions_2024.csv', header=None, names=transactions_columns)

df_transactions_2024

,Transaction Unique Identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status
0,{2131FCF5-B031-86E8-E063-4804A8C0372B},320000,2024-07-26 00:00,MK40 3SG,T,N,F,38,NaN,GEORGE STREET,NaN,BEDFORD,BEDFORD,BEDFORD,A,A
1,{2131FCF5-B034-86E8-E063-4804A8C0372B},300000,2024-02-15 00:00,MK43 9GH,S,N,F,12,NaN,BRICK CRESCENT,STEWARTBY,BEDFORD,BEDFORD,BEDFORD,A,A
2,{2131FCF5-B036-86E8-E063-4804A8C0372B},470000,2024-08-21 00:00,MK45 2BF,S,N,F,21,NaN,COLTSFOOT CORNER,AMPTHILL,BEDFORD,CENTRAL BEDFORDSHIRE,CENTRAL BEDFORDSHIRE,A,A
3,{2131FCF5-B037-86E8-E063-4804A8C0372B},527500,2024-07-29 00:00,MK43 0YX,D,N,L,1,NaN,FALLOWS CRESCENT,CRANFIELD,BEDFORD,CENTRAL BEDFORDSHIRE,CENTRAL BEDFORDSHIRE,A,A
4,{2131FCF5-B038-86E8-E063-4804A8C0372B},351000,2024-07-17 00:00,LU3 3AR,T,N,F,320,NaN,SUNDON PARK ROAD,NaN,LUTON,LUTON,LUTON,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913315,{1EAE3DF7-2F7E-9EB1-E063-4704A8C09D02},249500,2024-07-08 00:00,TA20 2QR,S,N,F,29,NaN,LINKHAY ORCHARD,SOUTH CHARD,CHARD,SOMERSET,SOMERSET,A,A
913316,{1EAE3DF7-2F7F-9EB1-E063-4704A8C09D02},345000,2024-07-04 00:00,BA5 1UG,T,N,F,5,NaN,SOUTHOVER,NaN,WELLS,SOMERSET,SOMERSET,A,A
913317,{1EAE3DF7-2F80-9EB1-E063-4704A8C09D02},165000,2024-07-01 00:00,TA18 8DA,F,N,L,CHRISTCHURCH COURT,FLAT 4,SOUTH STREET,NaN,CREWKERNE,SOMERSET,SOMERSET,A,A
913318,{1EAE3DF7-2F81-9EB1-E063-4704A8C09D02},165000,2024-07-05 00:00,TA18 8ES,T,N,F,8,NaN,HERMITAGE STREET,NaN,CREWKERNE,SOMERSET,SOMERSET,A,A
913319,{1EAE3DF7-2F82-9EB1-E063-4704A8C09D02},220000,2024-06-28 00:00,TA14 6PS,T,N,F,34,NaN,HIGH STREET,NaN,STOKE-SUB-HAMDON,SOMERSET,SOMERSET,A,A